#!/usr/bin/env python3
"""
diagnose-approval.py — Trace an approval ID to its source cron and agent.

Usage:
  python3 diagnose-approval.py <id-or-prefix>
  python3 diagnose-approval.py 2f2894a3
  python3 diagnose-approval.py --by-time HH:MM   # find crons firing at UTC time
  python3 diagnose-approval.py --recent          # show last 10 runs across all crons

This is the tool Mr Fixit MUST run before claiming a root cause for an
approval prompt. Never guess from symptoms.

How it works:
  OpenClaw 2026.4.10 does NOT store pending approvals on disk. Pending approval
  ids live in-memory inside the gateway. BUT — when a cron run requests an
  approval, the request text (including the approval id) lands in the cron run
  history's `summary` field, accessible via `openclaw cron runs --id <jobId>`.

  So to map an approval id to its source cron:
    1. List all crons via `openclaw cron list`
    2. For each cron, fetch recent runs via `openclaw cron runs --id <jobId>`
    3. Search the JSON `summary` field for the approval id prefix
    4. Print the matching cron name, schedule, and run details

Exit codes:
  0 = found and printed forensics
  1 = id not found anywhere
  2 = tooling error (openclaw CLI missing, etc.)
"""

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone


def run(cmd, timeout=20):
    """Run command, return (returncode, stdout, stderr)."""
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout or "", r.stderr or ""
    except FileNotFoundError:
        return 127, "", f"command not found: {cmd[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", f"timeout after {timeout}s"
    except Exception as e:
        return 1, "", str(e)


CRON_LINE_RE = re.compile(
    r"^(?P<id>[a-f0-9-]{36})\s+"
    r"(?P<name>\S+)\s+"
    r"cron\s+(?P<schedule>(?:[\S]+\s){4}[\S]+)"
    r".*?(?P<agent>\S+)\s+\S+\s*$"
)


def list_crons():
    """Return list of {id, name, schedule, agent} dicts from `openclaw cron list`."""
    rc, out, err = run(["openclaw", "cron", "list"])
    if rc != 0:
        return None, f"openclaw cron list failed: {err or out}"

    crons = []
    for line in out.splitlines():
        line = line.rstrip()
        if not line.strip():
            continue
        m = re.match(r"^([a-f0-9-]{36})\s+(\S+)\s+cron\s+(.+)$", line)
        if not m:
            continue
        job_id, name, rest = m.groups()
        sched_match = re.match(r"^((?:\S+\s+){4}\S+)", rest)
        schedule = sched_match.group(1) if sched_match else "?"
        tail = rest.split()
        agent = tail[-2] if len(tail) >= 2 else "?"
        crons.append({"id": job_id, "name": name, "schedule": schedule, "agent": agent})
    return crons, None


def get_runs(job_id, limit=10):
    """Return list of run dicts for a cron job, parsed from JSON."""
    rc, out, _ = run(
        ["openclaw", "cron", "runs", "--id", job_id, "--limit", str(limit)],
    )
    if rc != 0 or not out.strip():
        return []
    try:
        data = json.loads(out)
        return data.get("entries", [])
    except json.JSONDecodeError:
        return []


def search_runs_for_approval(id_prefix, crons):
    """Scan recent runs of all crons for the approval id prefix in the summary."""
    matches = []
    for cron in crons:
        runs = get_runs(cron["id"], limit=10)
        for r in runs:
            summary = (r.get("summary") or "")
            if id_prefix in summary:
                matches.append((cron, r))
                break
    return matches


def fmt_ts(ms):
    if not ms:
        return "?"
    try:
        dt = datetime.fromtimestamp(ms / 1000, tz=timezone.utc)
        return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return f"{ms} (raw)"


def diagnose_by_id(id_prefix):
    print(f"[diagnose-approval] searching for approval id prefix: {id_prefix}\n")
    crons, err = list_crons()
    if err:
        print(f"❌ {err}")
        return 2
    if not crons:
        print("❌ no crons returned by openclaw cron list")
        return 2

    print(f"   scanning {len(crons)} crons for recent runs containing '{id_prefix}'...\n")
    matches = search_runs_for_approval(id_prefix, crons)

    if not matches:
        print(f"❌ id '{id_prefix}' not found in any recent cron run summary.")
        print("   Possible causes:")
        print("     - The approval id is older than the cron run history retains")
        print("     - The id was generated by an interactive command, not a cron")
        print("     - You typed the prefix wrong")
        print("   Try: --by-time HH:MM with the timestamp from the approval prompt")
        return 1

    print(f"✅ found {len(matches)} match(es):\n")
    for cron, run_entry in matches:
        print(f"   cron name:    {cron['name']}")
        print(f"   agent:        {cron['agent']}")
        print(f"   schedule:     {cron['schedule']}")
        print(f"   job id:       {cron['id']}")
        print(f"   ran at:       {fmt_ts(run_entry.get('runAtMs') or run_entry.get('ts'))}")
        print(f"   status:       {run_entry.get('status', '?')}")
        print(f"   duration:     {run_entry.get('durationMs', '?')} ms")
        summary = run_entry.get("summary") or ""
        if len(summary) > 400:
            summary = summary[:400] + "..."
        print(f"   summary:      {summary}")
        print()

    print("[diagnose-approval] verdict: cite the cron name above in your reply.")
    print("                    if multiple matches, cite all of them.")
    return 0


def cron_field_matches(field, value):
    """Does a single cron field (* / 0-23 / */6 / 1,3 / 1-5) match the given int value?"""
    if field == "*":
        return True
    if "/" in field:
        base, step = field.split("/", 1)
        try:
            step = int(step)
        except ValueError:
            return False
        if base == "*":
            return value % step == 0
        try:
            return int(base) == value or (value > int(base) and (value - int(base)) % step == 0)
        except ValueError:
            return False
    for part in field.split(","):
        if "-" in part:
            try:
                lo, hi = part.split("-")
                if int(lo) <= value <= int(hi):
                    return True
            except ValueError:
                continue
        else:
            try:
                if int(part) == value:
                    return True
            except ValueError:
                continue
    return False


def diagnose_by_time(hh_mm):
    try:
        hour, minute = [int(x) for x in hh_mm.split(":")]
    except ValueError:
        print(f"❌ invalid time format. use HH:MM (got: {hh_mm})")
        return 2

    now = datetime.now(timezone.utc)
    weekday_cron = (now.weekday() + 1) % 7

    print(f"[diagnose-approval] searching crons that fire at {hh_mm} UTC")
    print(f"                   (today UTC is weekday {weekday_cron} in cron numbering)\n")

    crons, err = list_crons()
    if err:
        print(f"❌ {err}")
        return 2
    if not crons:
        print("❌ no crons returned")
        return 2

    matches = []
    for c in crons:
        sched = c["schedule"].split()
        if len(sched) < 5:
            continue
        f_minute, f_hour, f_dom, f_mon, f_dow = sched[:5]
        if not cron_field_matches(f_minute, minute):
            continue
        if not cron_field_matches(f_hour, hour):
            continue
        if not cron_field_matches(f_dow, weekday_cron):
            continue
        matches.append(c)

    if not matches:
        print("   no crons match this exact UTC time on today's weekday.")
        print("   try a different weekday number (0=Sun..6=Sat) by running `openclaw cron list`")
        print("   manually and grepping for the time field.")
        return 1

    print(f"   found {len(matches)} candidate cron(s):")
    for c in matches:
        print(f"   • {c['agent']}/{c['name']}")
        print(f"     schedule: {c['schedule']}")
        print(f"     job id:   {c['id']}")
    print()
    print("[diagnose-approval] verdict: cite one of these in your reply,")
    print("                    then run `openclaw cron runs --id <jobId>` to confirm.")
    return 0


def list_recent():
    crons, err = list_crons()
    if err:
        print(f"❌ {err}")
        return 2
    print(f"[diagnose-approval] last 10 runs of all crons:\n")
    all_runs = []
    for c in crons:
        for r in get_runs(c["id"], limit=10):
            r["_cron_name"] = c["name"]
            r["_agent"] = c["agent"]
            all_runs.append(r)
    all_runs.sort(key=lambda r: r.get("runAtMs") or r.get("ts") or 0, reverse=True)
    for r in all_runs[:10]:
        ts = fmt_ts(r.get("runAtMs") or r.get("ts"))
        summary = (r.get("summary") or "")[:120]
        print(f"   {ts}  {r['_agent']}/{r['_cron_name']}  {r.get('status', '?')}  {summary}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Trace approval IDs to source crons.")
    parser.add_argument("id_prefix", nargs="?", help="approval id or prefix")
    parser.add_argument("--recent", action="store_true", help="list recent runs across all crons")
    parser.add_argument("--by-time", metavar="HH:MM", help="find crons firing at UTC time")
    args = parser.parse_args()

    if args.recent:
        sys.exit(list_recent())
    if args.by_time:
        sys.exit(diagnose_by_time(args.by_time))
    if not args.id_prefix:
        parser.print_help()
        sys.exit(2)
    sys.exit(diagnose_by_id(args.id_prefix))


if __name__ == "__main__":
    main()
